import { EstadoConCiudadesDto } from "../ubicacion.dto";

export const ESTADOS_CIUDADES: EstadoConCiudadesDto[] = [
  {
    nombre: "Aguascalientes",
    ciudades: [
      "Aguascalientes (capital)",
      "Jesús María",
      "Calvillo",
      "Rincón de Romos",
      "Pabellón de Arteaga",
      "Asientos",
      "Cosío",
      "San José de Gracia",
      "Tepezalá",
      "El Llano",
      "San Francisco de los Romo",
      // Localidades adicionales por municipio:
      // Aguascalientes:
      "Palo Alto",
      "Norias del Paso Hondo",
      "Villa Lic. Jesús Terán (Calvillito)",
      // Jesús María:
      "Mirasol",
      "Solidaridad (Plutarco Elías Calles)",
      // Calvillo:
      "La Labor",
      "Las Ánimas",
      "Ojo de Agua de Crucitas",
      // Rincón de Romos:
      "El Bajío",
      "San Jacinto",
      // Pabellón de Arteaga:
      "Santiago",
      "El Gigante",
      // Asientos:
      "Guadalupe de Atlas",
      "Ciénega Grande",
      // Cosío:
      "Santa María de la Paz",
      "El Refugio de Agua Zarca",
      // San José de Gracia:
      "Paredes",
      "La Congoja",
      // Tepezalá:
      "El Chayote",
      "San Antonio",
      // El Llano:
      "Paso Blanco",
      "Los Conos",
      // San Francisco de los Romo:
      "El Puertecito",
      "Los Negritos",
    ],
  },
  {
    nombre: "Baja California",
    ciudades: [
      // Municipio de Mexicali:
      "Mexicali (capital)",
      "San Felipe",
      "Ciudad Guadalupe Victoria",
      "Los Algodones",
      "Progreso",
      "Villa del Campo",
      "Estación Delta",
      "Puebla",
      "Laguna Salada",
      "Islas Agrarias Grupo A",

      // Municipio de Tijuana:
      "Tijuana",
      "Rosarito (antes parte de Tijuana)",
      "La Mesa",
      "Otay Centenario",
      "Terrazas del Valle",
      "El Florido",
      "San Antonio del Mar",
      "Lomas del Porvenir",
      "Maclovio Rojas",

      // Municipio de Ensenada:
      "Ensenada",
      "Maneadero",
      "San Quintín",
      "El Sauzal",
      "Villa de Jesús María",
      "Ojos Negros",
      "Punta Colonet",
      "Bahía de los Ángeles",
      "Guerrero Negro (compartido con BCS)",
      "Chapultepec",

      // Municipio de Tecate:
      "Tecate",
      "La Rumorosa",
      "Valle de las Palmas",
      "Hacienda Tecate",
      "El Testerazo",
      "Jacume",

      // Municipio de Playas de Rosarito:
      "Playas de Rosarito",
      "Privada del Mar",
      "Colinas del Sol",
      "Baja Malibú",
      "Villa Turística",

      // Otras comunidades notables:
      "El Hongo",
      "Río Hardy",
      "Puerto Libertad",
      "Puertecitos",
      "Ejido Tabasco",
    ],
  },
  {
    nombre: "Baja California Sur",
    ciudades: [
      // Municipio de La Paz:
      "La Paz (capital)",
      "El Centenario",
      "Todos Santos",
      "El Pescadero",
      "Melitón Albáñez Domínguez",
      "San Pedro",
      "Chametla",
      "El Zacatal",
      "La Ventana",
      "Las Margaritas",
      "Puerto Chale",
      "San Juan de los Planes",

      // Municipio de Los Cabos:
      "San José del Cabo",
      "Cabo San Lucas",
      "Santiago",
      "Miraflores",
      "La Ribera",
      "Las Veredas",
      "El Campamento",
      "Caduaño",
      "Santa Anita",
      "La Playa",

      // Municipio de Loreto:
      "Loreto",
      "Puerto López Mateos",
      "Ligüí",
      "San Javier",
      "Ensenada Blanca",
      "Tembabiche",
      "Comondú Viejo",
      "La Purísima",
      "San Isidro",

      // Municipio de Mulegé:
      "Santa Rosalía",
      "Mulegé",
      "Guerrero Negro",
      "Bahía Tortugas",
      "Vizcaíno",
      "San Ignacio",
      "San Bruno",
      "Punta Abreojos",
      "El Datilar",
      "Punta Eugenia",

      // Municipio de Comondú:
      "Ciudad Constitución",
      "Puerto San Carlos",
      "Puerto Adolfo López Mateos",
      "San Juanico",
      "La Poza Grande",
      "Benito Juárez",
      "El Dátil",
      "La Purísima",
      "Isla Natividad",

      // Otras localidades destacadas:
      "Bahía Asunción",
      "Bahía Magdalena",
      "El Cardón",
      "Agua Amarga",
      "El Triunfo",
      "San Bartolo",
      "Las Cuevas",
      "El Sargento",
      "La Fortuna",
    ],
  },
  {
    nombre: "Campeche",
    ciudades: [
      // Municipio de Campeche (capital):
      "San Francisco de Campeche (capital)",
      "Lerma",
      "Chiná",
      "Pich",
      "Hampolol",
      "Tixmucuy",
      "Seybaplaya",
      "Tenabo",
      "Hool",
      "Castamay",
      "Dzibalchén",

      // Municipio de Ciudad del Carmen:
      "Ciudad del Carmen",
      "Isla Aguada",
      "Sabancuy",
      "Atasta",
      "Champotón",
      "Seybaplaya",
      "Lerma",
      "Pomuch",
      "Calkiní",
      "Bécal",
      "Nunkiní",

      // Municipio de Champotón:
      "Champotón (cabecera)",
      "Seybaplaya",
      "Hool",
      "Ulumal",
      "Xbacab",
      "Pocboc",
      "San Pablo Pixtún",
      "San Antonio Cayal",
      "San Francisco Kobén",
      "Santa Cruz Ex-Hacienda",

      // Municipio de Escárcega:
      "Escárcega",
      "Chiná",
      "Constitución",
      "División del Norte",
      "La Libertad",
      "Nuevo Coahuila",
      "Pueblo Nuevo",
      "Río Verde",
      "San Pedro",
      "Santa Rosalía",

      // Municipio de Calkiní:
      "Calkiní (cabecera)",
      "Bécal",
      "Nunkiní",
      "Tepakán",
      "Dzitbalché",
      "Santa Cruz Pueblo",
      "San Antonio Sahcabchén",
      "Tankuché",
      "Pucnachen",
      "San Nicolás",

      // Otras localidades destacadas:
      "Calakmul (zona arqueológica)",
      "Xpujil",
      "Zoh-Laguna",
      "Dzibalchén",
      "Hopelchén",
      "Bolonchén de Rejón",
      "Dzitbalché",
      "Ich-Ek",
      "Pomuch",
      "Xcalak",
    ],
  },
  {
    nombre: "Chiapas",
    ciudades: [
      // Región Centro (Tuxtla):
      "Tuxtla Gutiérrez (capital)",
      "Chiapa de Corzo",
      "Berriozábal",
      "Ocozocoautla",
      "Suchiapa",
      "Acala",
      "San Fernando",
      "Osumacinta",

      // Región Altos (San Cristóbal):
      "San Cristóbal de las Casas",
      "San Juan Chamula",
      "Zinacantán",
      "Amatenango del Valle",
      "Tenejapa",
      "San Andrés Larráinzar",
      "Chenalhó",
      "Huixtán",
      "Teopisca",

      // Fronteriza (Tapachula):
      "Tapachula",
      "Huixtla",
      "Cacahoatán",
      "Motozintla",
      "Tuzantán",
      "Metapa",
      "Unión Juárez",
      "Frontera Hidalgo",
      "Mazatán",

      // Soconusco (Costa):
      "Mapastepec",
      "Pijijiapan",
      "Acapetahua",
      "Huehuetán",
      "Villa Comaltitlán",
      "Escuintla",
      "Acacoyagua",

      // Selva Lacandona:
      "Palenque",
      "Ocosingo",
      "Altamirano",
      "Las Margaritas",
      "Benemérito de las Américas",
      "Marqués de Comillas",
      "Nueva Palestina",

      // Istmo-Costa:
      "Tonalá",
      "Arriaga",
      "Pueblo Nuevo Comaltitlán",
      "Huatulco (zona limítrofe)",

      // Valles Centrales (Comitán):
      "Comitán de Domínguez",
      "Las Rosas",
      "La Trinitaria",
      "La Independencia",
      "Socoltenango",
      "Tzimol",
      "Bella Vista",

      // Zonas Arqueológicas y Turísticas:
      "Bonampak",
      "Yaxchilán",
      "Toniná",
      "Chinkultic",
      "Lagunas de Montebello",
      "El Chiflón",
      "Cascadas de Agua Azul",
      "Misol-Há",

      // Otras comunidades destacadas:
      "Venustiano Carranza",
      "Simojovel",
      "El Bosque",
      "Pantelhó",
      "Aldama",
      "Mitontic",
      "Cancuc",
      "Oxchuc",
      "Aguacatenango",
    ],
  },
  {
    nombre: "Chihuahua",
    ciudades: [
      // Región Centro (Desierto):
      "Chihuahua (capital)",
      "Aldama",
      "Aquiles Serdán",
      "Santa Eulalia",
      "El Sauz",
      "Namiquipa",
      "Santa Isabel",
      "Satevó",

      // Frontera Norte (Juárez):
      "Ciudad Juárez",
      "Praxis (Anapra)",
      "San Agustín",
      "Guadalupe Distrito Bravos",
      "Loma Blanca",
      "Samalayuca",
      "Villa Ahumada",
      "Buenaventura",

      // Sierra Tarahumara:
      "Creel",
      "Batopilas",
      "Urique",
      "Guachochi",
      "Bocoyna",
      "Carichí",
      "Guadalupe y Calvo",
      "Maguarichi",
      "Nonava",
      "San Rafael",

      // Región Sur (Agricultura):
      "Delicias",
      "Meoqui",
      "Saucillo",
      "Camargo",
      "Julimes",
      "La Cruz",
      "Rosales",
      "San Francisco de Conchos",

      // Región Noroeste (Cuauhtémoc):
      "Cuauhtémoc",
      "Anáhuac",
      "Riva Palacio",
      "Cusihuiriachi",
      "Gran Morelos",
      "Santa Isabel",
      "Gómez Farías",

      // Región Sureste (Minera/Histórica):
      "Hidalgo del Parral",
      "Santa Bárbara",
      "San Francisco del Oro",
      "Allende",
      "López",
      "Matamoros",
      "Valle de Zaragoza",
      "Coronado",

      // Zonas Naturales y Turísticas:
      "Barrancas del Cobre",
      "Basaseachi (cascada)",
      "Cusárare",
      "Cerocahui",
      "Oteros",
      "Misión de San Javier",
      "Paquimé (zona arqueológica)",
      "Médanos de Samalayuca",

      // Otras comunidades destacadas:
      "Casas Grandes",
      "Nuevo Casas Grandes",
      "Janos",
      "Ascensión",
      "Ojinaga",
      "Manuel Benavides",
      "Coyame",
      "Santo Niño",
      "El Vergel",
    ],
  },
  {
    nombre: "Ciudad de México",
    ciudades: [
      "Álvaro Obregón",
      "Azcapotzalco",
      "Benito Juárez",
      "Coyoacán",
      "Cuauhtémoc",
      "Gustavo A. Madero",
      "Iztacalco",
      "Iztapalapa",
      "La Magdalena Contreras",
      "Miguel Hidalgo",
      "Milpa Alta",
      "Tláhuac",
      "Tlalpan",
      "Venustiano Carranza",
      "Xochimilco",
    ],
  },
  {
    nombre: "Coahuila",
    ciudades: [
      "Saltillo",
      "Torreón",
      "Monclova",
      "Piedras Negras",
      "Acuña",
      "Matamoros",
      "Sabinas",
      "San Pedro",
      "Frontera",
      "Nava",
      "Allende",
      "Morelos",
      "Zaragoza",
      "Múzquiz",
      "Progreso",
      "Viesca",
      "Castaños",
      "Ramos Arizpe",
      "Arteaga",
      "General Cepeda",
      "Parras de la Fuente",
      "Cuatro Ciénegas",
      "Ocampo",
      "Sierra Mojada",
      "Abasolo",
      "Guerrero",
      "Hidalgo",
      "Francisco I. Madero",
      "San Buenaventura",
      "Lamadrid",
      "Nadadores",
      "Sacramento",
      "San Juan de Sabinas",
      "Juárez",
      "Escobedo",
      "Villa Unión",
      "Candela",
      "Palau",
    ],
  },
  {
    nombre: "Colima",
    ciudades: [
      "Colima (capital)",
      "Manzanillo",
      "Tecomán",
      "Villa de Álvarez",
      "Coquimatlán",
      "Comala",
      "Minatitlán",
      "Armería",
      "Ixtlahuacán",
      "Cuauhtémoc",
      // Principales localidades por municipio:
      // Colima:
      "El Trapiche",
      "Tepames",
      "Zacualpan",
      // Manzanillo:
      "Salagua",
      "Santiago",
      "Las Brisas",
      "El Colomo",
      // Tecomán:
      "Cofradía de Juárez",
      "Caleras",
      "Tecuanillo",
      // Villa de Álvarez:
      "El Chanal",
      "La Estancia",
      "La Piedra Lisa",
      // Coquimatlán:
      "Paso del Zarco",
      "Los Asmoles",
      // Comala:
      "Suchitlán",
      "Zacualpan",
      "La Nogalera",
      // Minatitlán:
      "El Naranjo",
      "Peña Colorada",
      // Armería:
      "Rincón de López",
      "Cuyutlán",
      // Ixtlahuacán:
      "El Camichín",
      "Agua Dulce",
      // Cuauhtémoc:
      "Quesería",
      "Alzada",
      // Otras localidades relevantes:
      "Piscila",
      "Chanquiahuitl",
      "El Mixcuate",
      "La Palmera",
      "La Central",
    ],
  },
  {
    nombre: "Durango",
    ciudades: [
      // Principales ciudades
      "Durango (Victoria de Durango)",
      "Gómez Palacio",
      "Lerdo",
      "Cuencamé",
      "Canatlán",

      // Otras cabeceras municipales
      "Santa María del Oro",
      "Peñón Blanco",
      "Nazas",
      "San Juan del Río",
      "Indé",
      "San Luis del Cordero",
      "Poanas",
      "Mapimí",
      "Tlahualilo",
      "Hidalgo",
      "Ocampo",
      "Guanaceví",
      "El Oro",
      "San Dimas",
      "Tamazula",
      "Topia",
      "Tepehuanes",
      "Mezquital",
      "Pueblo Nuevo",
      "San Bernardo",
      "Otáez",
      "Súchil",
      "Nuevo Ideal",
      "Rodeo",
      "Coneto de Comonfort",
      "Pánuco de Coronado",
      "General Simón Bolívar",

      // Localidades importantes por región
      // Zona Metropolitana Lagunera:
      "Ciudad Lerdense",
      "La Loma",
      "Las Flores",

      // Región de los Llanos:
      "Vicente Guerrero",
      "Pánuco",
      "Ignacio Allende",

      // Región Sierra:
      "Guadalupe Victoria",
      "Santiago Papasquiaro",
      "Canelas",
      "San Miguel de Cruces",

      // Zonas turísticas/mineras:
      "Nombre de Dios (pueblo histórico)",
      "La Ferrería (zona arqueológica)",
      "La Ciudad (zona minera)",
      "El Salto (cascada)",

      // Comunidades rurales destacadas:
      "La Soledad",
      "San Jacinto",
      "El Refugio",
      "Las Nieves",
      "San Francisco del Mezquital",
    ],
  },
  {
    nombre: "Guanajuato",
    ciudades: [
      // Principales ciudades
      "León de los Aldama",
      "Guanajuato (capital)",
      "Irapuato",
      "Celaya",
      "Salamanca",

      // Todas las cabeceras municipales (46)
      "Acámbaro",
      "San Miguel de Allende",
      "Dolores Hidalgo",
      "San Felipe",
      "Silao",
      "San Francisco del Rincón",
      "Pénjamo",
      "Manuel Doblado",
      "Purísima del Rincón",
      "Romita",
      "San José Iturbide",
      "Apaseo el Alto",
      "Apaseo el Grande",
      "Atarjea",
      "Coroneo",
      "Cortazar",
      "Cuerámaro",
      "Doctor Mora",
      "Abasolo",
      "Huanímaro",
      "Jaral del Progreso",
      "Jerécuaro",
      "Moroleón",
      "Ocampo",
      "Pueblo Nuevo",
      "Santa Cruz de Juventino Rosas",
      "Santiago Maravatío",
      "Tarandacuao",
      "Tarimoro",
      "Tierra Blanca",
      "Uriangato",
      "Valle de Santiago",
      "Victoria",
      "Villagrán",
      "Xichú",
      "Yuriria",

      // Pueblos Mágicos
      "Mineral de Pozos",
      "Salvatierra",
      "Jalpa de Cánovas",

      // Otras localidades importantes
      "Comonfort",
      "Santa Ana Pacueco",
      "La Calera",
      "La Moncada",
      "Cerro Gordo",
      "La Ermita",
      "San Roque",
      "San Pedro de los Nietos",

      // Zonas industriales/turísticas
      "Puerto Interior (Silao)",
      "Parque Industrial FIPASI (Irapuato)",
      "Zona Arqueológica Peralta (Abasolo)",
      "Plaza Mayor (León)",
      "Ex-Hacienda San Gabriel de Barrera (Guanajuato)",
    ],
  },
  {
    nombre: "Guerrero",
    ciudades: [
      // Principales ciudades turísticas y capital
      "Acapulco de Juárez",
      "Chilpancingo de los Bravo (capital)",
      "Iguala de la Independencia",
      "Taxco de Alarcón",
      "Zihuatanejo de Azueta",

      // Cabeceras municipales (81 en total)
      "Altamirano",
      "Apaxtla",
      "Arcelia",
      "Atenango del Río",
      "Atlamajalcingo del Monte",
      "Atlixtac",
      "Atoyac de Álvarez",
      "Ayutla de los Libres",
      "Azoyú",
      "Benito Juárez",
      "Buenavista de Cuéllar",
      "Chilapa de Álvarez",
      "Cocula",
      "Copala",
      "Copalillo",
      "Coyuca de Benítez",
      "Coyuca de Catalán",
      "Cuajinicuilapa",
      "Cualac",
      "Cuautepec",
      "Cuetzala del Progreso",
      "Cutzamala de Pinzón",
      "Eduardo Neri",
      "Florencio Villarreal",
      "General Canuto A. Neri",
      "General Heliodoro Castillo",
      "Huamuxtitlán",
      "Huitzuco de los Figueroa",
      "Juan R. Escudero",
      "Juchitán",
      "La Unión de Isidoro Montes de Oca",
      "Leonardo Bravo",
      "Malinaltepec",
      "Marquelia",
      "Mártir de Cuilapan",
      "Metlatónoc",
      "Mochitlán",
      "Olinalá",
      "Ometepec",
      "Pedro Ascencio Alquisiras",
      "Petatlán",
      "Pilcaya",
      "Pungarabato",
      "Quechultenango",
      "San Luis Acatlán",
      "San Marcos",
      "San Miguel Totolapan",
      "Tecoanapa",
      "Técpan de Galeana",
      "Teloloapan",
      "Tepecoacuilco de Trujano",
      "Tetipac",
      "Tixtla de Guerrero",
      "Tlacoachistlahuaca",
      "Tlacoapa",
      "Tlalchapa",
      "Tlalixtaquilla de Maldonado",
      "Tlapa de Comonfort",
      "Tlapehuala",
      "Xalpatláhuac",
      "Xochihuehuetlán",
      "Xochistlahuaca",
      "Zapotitlán Tablas",
      "Zirándaro",
      "Zitlala",

      // Pueblos Mágicos y destinos turísticos
      "Ixtapa",
      "Barra de Potosí",
      "Playa Ventura",
      "El Paraíso",
      "Copa del Sol",
      "Pie de la Cuesta",
      "Lagunas de Chacahua",

      // Zonas arqueológicas
      "La Soledad de Maciel",
      "Tehuacalco",
      "Palmillas",

      // Comunidades indígenas importantes
      "Alcozauca",
      "Xochapa",
      "Olinalá (lugar artesanal)",
      "Malinaltepec (comunidad tlapaneca)",
      "Tlacoachistlahuaca (comunidad amuzga)",

      // Playas destacadas
      "Playa Revolcadero",
      "Barra Vieja",
      "Playa Larga",
      "Playa Troncones",
      "Playa Majahua",
    ],
  },
  {
    nombre: "Hidalgo",
    ciudades: [
      // Principales ciudades
      "Pachuca de Soto (capital)",
      "Tulancingo de Bravo",
      "Tizayuca",
      "Huichapan",
      "Apan",

      // Todas las cabeceras municipales (84)
      "Acatlán",
      "Acaxochitlán",
      "Actopan",
      "Agua Blanca de Iturbide",
      "Ajacuba",
      "Alfajayucan",
      "Almoloya",
      "Apan",
      "Atitalaquia",
      "Atlapexco",
      "Atotonilco el Grande",
      "Atotonilco de Tula",
      "Calnali",
      "Cardonal",
      "Chapantongo",
      "Chapulhuacán",
      "Chilcuautla",
      "Cuautepec de Hinojosa",
      "El Arenal",
      "Eloxochitlán",
      "Emiliano Zapata",
      "Epazoyucan",
      "Francisco I. Madero",
      "Huasca de Ocampo",
      "Huautla",
      "Huazalingo",
      "Huehuetla",
      "Huejutla de Reyes",
      "Huichapan",
      "Ixmiquilpan",
      "Jacala de Ledezma",
      "Jaltocán",
      "Juárez Hidalgo",
      "La Misión",
      "Lolotla",
      "Metepec",
      "Metztitlán",
      "Mineral de la Reforma",
      "Mineral del Chico",
      "Mineral del Monte",
      "Mixquiahuala de Juárez",
      "Molango de Escamilla",
      "Nicolás Flores",
      "Nopala de Villagrán",
      "Omitlán de Juárez",
      "Pachuca de Soto",
      "Pacula",
      "Pisaflores",
      "Progreso de Obregón",
      "San Agustín Metzquititlán",
      "San Agustín Tlaxiaca",
      "San Bartolo Tutotepec",
      "San Felipe Orizatlán",
      "San Salvador",
      "Santiago de Anaya",
      "Santiago Tulantepec de Lugo Guerrero",
      "Singuilucan",
      "Tasquillo",
      "Tecozautla",
      "Tenango de Doria",
      "Tepeapulco",
      "Tepehuacán de Guerrero",
      "Tepeji del Río de Ocampo",
      "Tepetitlán",
      "Tetepango",
      "Tezontepec de Aldama",
      "Tianguistengo",
      "Tizayuca",
      "Tlahuelilpan",
      "Tlahuiltepa",
      "Tlanalapa",
      "Tlanchinol",
      "Tlaxcoapan",
      "Tolcayuca",
      "Tula de Allende",
      "Tulancingo de Bravo",
      "Villa de Tezontepec",
      "Xochiatipan",
      "Xochicoatlán",
      "Yahualica",
      "Zacualtipán de Ángeles",
      "Zapotlán de Juárez",
      "Zempoala",
      "Zimapán",

      // Pueblos Mágicos
      "Huasca de Ocampo",
      "Real del Monte",
      "Mineral del Chico",

      // Zonas arqueológicas
      "Tula (zona arqueológica)",
      "Xihuingo (Tepeapulco)",

      // Destinos turísticos importantes
      "Prismas Basálticos",
      "Grutas de Tolantongo",
      "Balneario de Tecozautla",
      "Presa Endhó",
      "Bosque de las Truchas",

      // Ciudades industriales
      "Ciudad Sahagún",
      "Parque Industrial Tizayuca",
      "Corredor Industrial Querétaro-Pachuca",
    ],
  },
  {
    nombre: "Jalisco",
    ciudades: [
      // Zona Metropolitana de Guadalajara
      "Guadalajara",
      "Zapopan",
      "Tlaquepaque",
      "Tonalá",
      "Tlajomulco de Zúñiga",
      "El Salto",
      "Ixtlahuacán de los Membrillos",
      "Juanacatlán",

      // Principales ciudades turísticas
      "Puerto Vallarta",
      "Ajijic",
      "Chapala",
      "Tapalpa",
      "Mazamitla",
      "Tequila",
      "San Juan de los Lagos",
      "Lagos de Moreno",

      // Cabeceras municipales (125 municipios)
      "Acatlán de Juárez",
      "Ahualulco de Mercado",
      "Amacueca",
      "Amatitán",
      "Ameca",
      "Arandas",
      "Atemajac de Brizuela",
      "Atengo",
      "Atenguillo",
      "Atotonilco el Alto",
      "Atoyac",
      "Autlán de Navarro",
      "Ayotlán",
      "Ayutla",
      "Bolaños",
      "Cabo Corrientes",
      "Casimiro Castillo",
      "Cihuatlán",
      "Cocula",
      "Colotlán",
      "Concepción de Buenos Aires",
      "Cuautitlán de García Barragán",
      "Cuautla",
      "Degollado",
      "Ejutla",
      "El Arenal",
      "El Grullo",
      "El Limón",
      "Encarnación de Díaz",
      "Etzatlán",
      "Guachinango",
      "Hostotipaquillo",
      "Huejúcar",
      "Huejuquilla el Alto",
      "Jalostotitlán",
      "Jamay",
      "Jesús María",
      "Jilotlán de los Dolores",
      "Jocotepec",
      "La Barca",
      "La Huerta",
      "La Manzanilla de la Paz",
      "Magdalena",
      "Mascota",
      "Mexticacán",
      "Mezquitic",
      "Mixtlán",
      "Ocotlán",
      "Ojuelos de Jalisco",
      "Pihuamo",
      "Poncitlán",
      "Quitupan",
      "San Cristóbal de la Barranca",
      "San Diego de Alejandría",
      "San Gabriel",
      "San Ignacio Cerro Gordo",
      "San Julián",
      "San Marcos",
      "San Martín de Bolaños",
      "San Martín Hidalgo",
      "San Miguel el Alto",
      "San Sebastián del Oeste",
      "Santa María de los Ángeles",
      "Sayula",
      "Tala",
      "Talpa de Allende",
      "Tamazula de Gordiano",
      "Tapalpa",
      "Tecalitlán",
      "Tecolotlán",
      "Techaluta de Montenegro",
      "Tenamaxtlán",
      "Teocaltiche",
      "Teocuitatlán de Corona",
      "Tepatitlán de Morelos",
      "Tequila",
      "Teuchitlán",
      "Tizapán el Alto",
      "Tlajomulco de Zúñiga",
      "Tomatlán",
      "Tuxcacuesco",
      "Tuxcueca",
      "Tuxpan",
      "Unión de San Antonio",
      "Unión de Tula",
      "Valle de Guadalupe",
      "Valle de Juárez",
      "Villa Corona",
      "Villa Guerrero",
      "Villa Hidalgo",
      "Villa Purificación",
      "Yahualica de González Gallo",
      "Zacoalco de Torres",
      "Zapotiltic",
      "Zapotitlán de Vadillo",
      "Zapotlán del Rey",
      "Zapotlán el Grande",
      "Zapotlanejo",

      // Pueblos Mágicos
      "Mascota",
      "Talpa de Allende",
      "San Sebastián del Oeste",
      "Tequila",
      "Mazamitla",
      "Tapalpa",
      "Lagos de Moreno",
      "Tlaquepaque",

      // Playas importantes
      "Yelapa",
      "Mismaloya",
      "Bucerías",
      "Punta Mita",
      "Barra de Navidad",
      "Melaque",
      "Tenacatita",
      "Costa Alegre",

      // Zonas arqueológicas
      "Guachimontones (Tequila)",
      "Ixtépete (Zapopan)",
      "El Grillo (Tlajomulco)",
    ],
  },
  {
    nombre: "Estado de México",
    ciudades: [
      // Principales ciudades (Área Metropolitana del Valle de México)
      "Toluca de Lerdo (capital)",
      "Ecatepec de Morelos",
      "Ciudad Nezahualcóyotl",
      "Naucalpan de Juárez",
      "Tlalnepantla de Baz",

      // Zona Metropolitana del Valle de México (parte Edomex)
      "Cuautitlán Izcalli",
      "Chimalhuacán",
      "Atizapán de Zaragoza",
      "Tultitlán",
      "Ixtapaluca",
      "Nicolás Romero",
      "Coacalco de Berriozábal",
      "Chalco",
      "Valle de Chalco Solidaridad",
      "Huixquilucan",
      "Zumpango",
      "Tecámac",
      "Texcoco",
      "Acolman",
      "Teotihuacán",

      // Ciudades industriales importantes
      "Lerma",
      "San Mateo Atenco",
      "Metepec",
      "Zinacantepec",
      "Jilotepec",
      "Atlacomulco",
      "Tepotzotlán",

      // Pueblos Mágicos y turísticos
      "Valle de Bravo",
      "Malinalco",
      "El Oro",
      "Aculco",
      "Villa del Carbón",
      "Ixtapan de la Sal",
      "Tonatico",
      "Tejupilco",

      // Cabeceras municipales (125 municipios)
      "Almoloya de Juárez",
      "Amanalco",
      "Amatepec",
      "Apaxco",
      "Atizapán",
      "Axapusco",
      "Ayapango",
      "Calimaya",
      "Capulhuac",
      "Chicoloapan",
      "Chiconcuac",
      "Donato Guerra",
      "Ecatzingo",
      "Huehuetoca",
      "Hueypoxtla",
      "Isidro Fabela",
      "Ixtapan del Oro",
      "Ixtlahuaca",
      "Jaltenco",
      "Jilotepec",
      "Joquicingo",
      "Juchitepec",
      "La Paz",
      "Luvianos",
      "Melchor Ocampo",
      "Nextlalpan",
      "Ocoyoacac",
      "Otzoloapan",
      "Otzolotepec",
      "Ozumba",
      "Papalotla",
      "Polotitlán",
      "Rayón",
      "San Antonio la Isla",
      "San Felipe del Progreso",
      "San José del Rincón",
      "San Martín de las Pirámides",
      "San Simón de Guerrero",
      "Santo Tomás",
      "Soyaniquilpan",
      "Sultepec",
      "Temoaya",
      "Tenango del Aire",
      "Tenango del Valle",
      "Tepetlaoxtoc",
      "Tepetlixpa",
      "Tequixquiac",
      "Timilpan",
      "Tlalmanalco",
      "Tonanitla",
      "Tultepec",
      "Villa Guerrero",
      "Xalatlaco",
      "Xonacatlán",
      "Zacazonapan",
      "Zacualpan",

      // Zonas arqueológicas
      "Teotihuacán (zona arqueológica)",
      "Calixlahuaca (Toluca)",
      "Huamango (Acambay)",

      // Áreas naturales
      "Nevado de Toluca",
      "Parque Nacional Izta-Popo",
      "Presas del Sistema Cutzamala",
      "Grutas de la Estrella",
      "Cascadas de Nanchititla",
    ],
  },
  {
    nombre: "Michoacán",
    ciudades: [
      // Principales ciudades
      "Morelia (capital)",
      "Zamora de Hidalgo",
      "Lázaro Cárdenas",
      "Pátzcuaro",

      // Cabeceras municipales (113 municipios)
      "Acuitzio",
      "Aguililla",
      "Álvaro Obregón",
      "Angamacutiro",
      "Angangueo",
      "Apatzingán",
      "Aporo",
      "Aquila",
      "Ario",
      "Arteaga",
      "Briseñas",
      "Buenavista",
      "Carácuaro",
      "Charapan",
      "Charo",
      "Chavinda",
      "Cherán",
      "Chilchota",
      "Chinicuila",
      "Chucándiro",
      "Churintzio",
      "Churumuco",
      "Coahuayana",
      "Coalcomán de Vázquez Pallares",
      "Coeneo",
      "Cojumatlán de Régules",
      "Contepec",
      "Copándaro",
      "Cotija",
      "Cuitzeo",
      "Ecuandureo",
      "Epitacio Huerta",
      "Erongarícuaro",
      "Gabriel Zamora",
      "Hidalgo",
      "Huandacareo",
      "Huaniqueo",
      "Huetamo",
      "Huiramba",
      "Indaparapeo",
      "Irimbo",
      "Ixtlán",
      "Jacona",
      "Jiménez",
      "Jiquilpan",
      "José Sixto Verduzco",
      "Juárez",
      "Jungapeo",
      "La Piedad",
      "Lagunillas",
      "Los Reyes",
      "Madero",
      "Maravatío",
      "Marcos Castellanos",
      "Morelos",
      "Múgica",
      "Nahuatzen",
      "Nocupétaro",
      "Nuevo Parangaricutiro",
      "Nuevo Urecho",
      "Numarán",
      "Ocampo",
      "Pajacuarán",
      "Panindícuaro",
      "Paracho",
      "Parácuaro",
      "Penjamillo",
      "Peribán",
      "Purépero",
      "Puruándiro",
      "Queréndaro",
      "Quiroga",
      "Sahuayo",
      "Salvador Escalante",
      "San Lucas",
      "Santa Ana Maya",
      "Senguio",
      "Susupuato",
      "Tacámbaro",
      "Tancítaro",
      "Tangamandapio",
      "Tangancícuaro",
      "Tanhuato",
      "Taretan",
      "Tarímbaro",
      "Tepalcatepec",
      "Tingambato",
      "Tingüindín",
      "Tiquicheo de Nicolás Romero",
      "Tlalpujahua",
      "Tlazazalca",
      "Tocumbo",
      "Tumbiscatío",
      "Turicato",
      "Tuxpan",
      "Tuzantla",
      "Tzintzuntzan",
      "Tzitzio",
      "Uruapan",
      "Venustiano Carranza",
      "Villamar",
      "Vista Hermosa",
      "Yurécuaro",
      "Zacapu",
      "Zamora",
      "Zináparo",
      "Zinapécuaro",
      "Ziracuaretiro",
      "Zitácuaro",

      // Pueblos Mágicos
      "Santa Clara del Cobre",

      // Zonas arqueológicas
      "Tzintzuntzan (yacimiento purépecha)",
      "Ihuatzio",
      "Tres Cerritos",
      "San Felipe los Alzati",

      // Reservas naturales
      "Reserva de la Biosfera Mariposa Monarca",
      "Parque Nacional Pico de Tancítaro",
      "Lago de Zirahuén",
      "Isla de Janitzio",
      "Cascadas de Tzaráracua",

      // Playas y costas
      "Playa Azul",
      "Caleta de Campos",
      "Boca de Apiza",
      "La Ticla",
      "Maruata",

      // Ciudades industriales
      "Zamora (corredor agroindustrial)",
    ],
  },
  {
    nombre: "Morelos",
    ciudades: [
      // Principales ciudades
      "Cuernavaca (capital)",
      "Jiutepec",
      "Cuautla",
      "Yautepec",

      // Todos los municipios (36)
      "Amacuzac",
      "Atlatlahucan",
      "Axochiapan",
      "Ayala",
      "Coatlán del Río",
      "Emiliano Zapata",
      "Huitzilac",
      "Jantetelco",
      "Jonacatepec",
      "Mazatepec",
      "Miacatlán",
      "Ocuituco",
      "Puente de Ixtla",
      "Temixco",
      "Temoac",
      "Tepalcingo",
      "Tepoztlán",
      "Tetecala",
      "Tetela del Volcán",
      "Tlalnepantla",
      "Tlaltizapán",
      "Tlaquiltenango",
      "Tlayacapan",
      "Totolapan",
      "Xochitepec",
      "Zacatepec",
      "Zacualpan de Amilpas",

      // Zonas arqueológicas
      "Xochicalco",
      "Teopanzolco",
      "Las Pilas (Jonacatepec)",
      "Chalcatzingo",

      // Balnearios y atractivos turísticos
      "Agua Hedionda",
      "Las Estacas",
      "Oaxtepec",
      "Hacienda Cocoyoc",
      "Balneario El Almeal",
      "Grutas de Cacahuamilpa",

      // Áreas naturales
      "Laguna de Hueyapan",
      "Parque El Tepozteco",
      "Sierra de Huautla",
      "Volcán Popocatépetl (zona limítrofe)",

      // Ciudades industriales
      "CIVAC (Jiutepec)",
      "Parque Industrial Cuautla",
    ],
  },
  {
    nombre: "Nayarit",
    ciudades: [
      // Principales ciudades
      "Tepic (capital)",
      "Compostela",
      "Bahía de Banderas",
      "Santiago Ixcuintla",
      "Acaponeta",

      // Todos los municipios (20)
      "Ahuacatlán",
      "Amatlán de Cañas",
      "Del Nayar",
      "Huajicori",
      "Ixtlán del Río",
      "Jala",
      "La Yesca",
      "Rosamorada",
      "Ruiz",
      "San Blas",
      "San Pedro Lagunillas",
      "Santa María del Oro",
      "Tecuala",
      "Tuxpan",
      "Xalisco",

      // Pueblos Mágicos
      "Jala",
      "Mexcaltitán",

      // Playas y destinos turísticos
      "Rincón de Guayabitos",
      "La Peñita de Jaltemba",
      "Sayulita",
      "San Pancho (San Francisco)",
      "Lo de Marcos",
      "Punta de Mita (compartido con Jalisco)",
      "Chacala",
      "Playa Los Ayala",
      "Islas Marías",

      // Zonas arqueológicas
      "Los Toriles (Ixtlán del Río)",
      "Coamiles (Tecuala)",

      // Comunidades indígenas
      "Santa Teresa (comunidad wixárika)",
      "San Andrés Cohamiata",
      "Tatei Kie (San Sebastián Teponahuaxtlán)",

      // Áreas naturales protegidas
      "Parque Nacional Isla Isabel",
      "Reserva de la Biosfera Marismas Nacionales",
      "Volcán Ceboruco",
      "Cerro de San Juan",
      "Cascada El Cora",

      // Ciudades agrícolas/industriales
      "Villa Hidalgo (El Nayar)",
      "Tuxpan (centro agrícola)",
      "Ruiz (nudo carretero)",
      "Xalisco (zona metropolitana de Tepic)",
    ],
  },
  {
    nombre: "Nuevo León",
    ciudades: [
      // Zona Metropolitana de Monterrey (principales municipios)
      "Monterrey",
      "San Pedro Garza García",
      "Guadalupe",
      "Apodaca",
      "San Nicolás de los Garza",
      "Santa Catarina",
      "General Escobedo",
      "García",
      "Juárez",

      // Otros municipios importantes (51 municipios total)
      "Abasolo",
      "Agualeguas",
      "Allende",
      "Anáhuac",
      "Aramberri",
      "Bustamante",
      "Cadereyta Jiménez",
      "Cerralvo",
      "China",
      "Doctor Arroyo",
      "Doctor Coss",
      "Doctor González",
      "Galeana",
      "General Bravo",
      "General Terán",
      "General Treviño",
      "General Zaragoza",
      "General Zuazua",
      "Hidalgo",
      "Higueras",
      "Hualahuises",
      "Iturbide",
      "Lampazos de Naranjo",
      "Linares",
      "Los Aldamas",
      "Los Herreras",
      "Los Ramones",
      "Marín",
      "Melchor Ocampo",
      "Mier y Noriega",
      "Mina",
      "Montemorelos",
      "Parás",
      "Pesquería",
      "Rayones",
      "Sabinas Hidalgo",
      "Salinas Victoria",
      "Santiago",
      "Vallecillo",
      "Villaldama",

      // Ciudades industriales/clave
      "Pesquería (parques industriales)",
      "Ciénaga de Flores",
      "El Carmen",
      "Ciudad Benito Juárez",
      "Ciudad General Terán",

      // Pueblos Mágicos y turísticos
      "Santiago (Pueblo Mágico)",
      "Bustamante (grutas y pan de piloncillo)",
      "Linares (zona histórica)",
      "Villaldama (pueblo histórico)",

      // Áreas naturales
      "Parque Nacional Cumbres de Monterrey",
      "Cola de Caballo (cascada)",
      "Grutas de Bustamante",
      "Presa de la Boca",
      "Cerro de la Silla",
      "Biósfera El Cielo (zona limítrofe con Tamaulipas)",

      // Zonas en desarrollo
      "Ciudad Aeropuerto (en desarrollo)",
      "Huasteca (zona metropolitana)",
      "Carretera Nacional (corredor industrial)",
    ],
  },
  {
    nombre: "Oaxaca",
    ciudades: [
      // Principales ciudades
      "Oaxaca de Juárez (capital)",
      "Salina Cruz",
      "Heroica Ciudad de Juchitán de Zaragoza",
      "Puerto Escondido",
      "Heroica Ciudad de Huajuapan de León",

      // Cabeceras municipales (570 municipios, principales)
      "San Juan Bautista Tuxtepec",
      "Santa Lucía del Camino",
      "San Antonio de la Cal",
      "Santa Cruz Xoxocotlán",
      "Santo Domingo Tehuantepec",
      "San Pedro Mixtepec",
      "San Pedro Pochutla",
      "San Sebastián Tutla",
      "Santa María Atzompa",
      "Santa María Huatulco",
      "Santiago Pinotepa Nacional",
      "Matías Romero Avendaño",
      "Loma Bonita",
      "San Pablo Villa de Mitla",
      "San Juan Bautista Cuicatlán",
      "San Pedro Tapanatepec",
      "San Miguel el Grande",
      "Villa de Tamazulápam del Progreso",
      "Villa de Zaachila",
      "Villa de Etla",
      "Asunción Nochixtlán",
      "Magdalena Tequisistlán",
      "San Dionisio del Mar",
      "San Francisco del Mar",
      "San Mateo del Mar",
      "Santiago Jamiltepec",
      "Putla Villa de Guerrero",
      "Miahuatlán de Porfirio Díaz",
      "Zimatlán de Álvarez",
      "Ejutla de Crespo",
      "San Jerónimo Tlacochahuaya",
      "San Bartolo Coyotepec",
      "San Martín Tilcajete",
      "San Agustín de las Juntas",
      "San Andrés Huayápam",
      "San Felipe Tejalápam",
      "San Jacinto Amilpas",
      "San Raymundo Jalpan",
      "San Sebastián Abasolo",
      "Santa Catarina Quiané",
      "Santa Cruz Amilpas",
      "Santa María Coyotepec",
      "Santa María del Tule",
      "Santiago Suchilquitongo",
      "Santo Domingo Tomaltepec",
      "Vicente Camalote",
      "Villa de Chilapa de Díaz",
      "Villa Sola de Vega",
      "Villa Talea de Castro",
      "Villa Tejúpam de la Unión",

      // Pueblos Mágicos
      "Capulálpam de Méndez",
      "Huautla de Jiménez",
      "Mazunte",
      "San Pablo Villa de Mitla",
      "San Pedro y San Pablo Teposcolula",
      "Santa Catarina Juquila",

      // Zonas arqueológicas
      "Monte Albán",
      "Mitla",
      "Yagul",
      "Atzompa",
      "Dainzú",
      "Lambityeco",
      "Zaachila",
      "Guilá Naquitz",
      "Huamelulpan",
      "San José el Mogote",

      // Playas y destinos turísticos
      "Bahías de Huatulco",
      "Mazunte",
      "Zipolite",
      "Puerto Ángel",
      "Carrizalillo",
      "Chacahua",
      "Laguna de Chacahua",
      "San Agustinillo",
      "La Ventanilla",
      "Playa Cangrejo",
      "Playa Coral",
      "Playa Estacahuite",
      "Playa La Boquilla",
      "Playa Mermejita",
      "Playa Rinconcito",
      "Playa Zicatela",

      // Comunidades indígenas destacadas
      "San Juan Chamula",
      "San Andrés Larráinzar",
      "San Juan Cancuc",
      "San Pedro Chenalhó",
      "Santiago el Pinar",
      "Aldama",
      "Chalchihuitán",
      "Pantelhó",
      "San Cristóbal de las Casas",
      "San Juan Bautista Valle Nacional",
      "San Lucas Ojitlán",
      "San Miguel Soyaltepec",
      "San Pedro Ixcatlán",
      "Santa María Jacatepec",
      "Santiago Jocotepec",
      "Totontepec Villa de Morelos",
      "San Juan Bautista Tlacoatzintepec",
      "San Juan Coatzóspam",
      "San Juan Comaltepec",
      "San Juan Lalana",
      "San Juan Petlapa",
      "San Juan Quiotepec",
      "San Juan Tabaá",
      "San Juan Tepeuxila",
      "San Juan Yaeé",
      "San Juan Yatzona",
      "San Juan Yucuita",
      "San Lucas Zoquiápam",
      "San Pedro Ocotepec",
      "San Pedro Sochiápam",
      "San Pedro Teutila",
      "San Pedro Yólox",
      "San Pedro Yucunama",
      "Santa María Alotepec",
      "Santa María Apazco",
      "Santa María Chachoápam",
      "Santa María Chilchotla",
      "Santa María Huazolotitlán",
      "Santa María Ixcatlán",
      "Santa María Jacatepec",
      "Santa María Jalapa del Marqués",
      "Santa María Jaltianguis",
      "Santa María la Asunción",
      "Santa María Nativitas",
      "Santa María Nduayaco",
      "Santa María Ozolotepec",
      "Santa María Pápalo",
      "Santa María Peñoles",
      "Santa María Quiegolani",
      "Santa María Sola",
      "Santa María Tataltepec",
      "Santa María Tecomavaca",
      "Santa María Temaxcalapa",
      "Santa María Teopoxco",
      "Santa María Tepantlali",
      "Santa María Texcatitlán",
      "Santa María Tlahuitoltepec",
      "Santa María Tlalixtac",
      "Santa María Tonameca",
      "Santa María Totolapilla",
      "Santa María Xadani",
      "Santa María Yalina",
      "Santa María Yavesía",
      "Santa María Yolotepec",
      "Santa María Yosoyúa",
      "Santa María Yucuhiti",
      "Santa María Zacatepec",
      "Santa María Zaniza",
      "Santa María Zoquitlán",
      "Santiago Amoltepec",
      "Santiago Apoala",
      "Santiago Apóstol",
      "Santiago Astata",
      "Santiago Atitlán",
      "Santiago Ayuquililla",
      "Santiago Cacaloxtepec",
      "Santiago Camotlán",
      "Santiago Chazumba",
      "Santiago Choápam",
      "Santiago Comaltepec",
      "Santiago del Río",
      "Santiago Huajolotitlán",
      "Santiago Huauclilla",
      "Santiago Ihuitlán Plumas",
      "Santiago Ixcuintepec",
      "Santiago Ixtayutla",
      "Santiago Jamiltepec",
      "Santiago Jocotepec",
      "Santiago Juxtlahuaca",
      "Santiago Lachiguiri",
      "Santiago Lalopa",
      "Santiago Laollaga",
      "Santiago Laxopa",
      "Santiago Llano Grande",
      "Santiago Matatlán",
      "Santiago Miltepec",
      "Santiago Minas",
      "Santiago Nacaltepec",
      "Santiago Nejapilla",
      "Santiago Niltepec",
      "Santiago Nundiche",
      "Santiago Nuyoó",
      "Santiago Pinotepa Nacional",
      "Santiago Suchilquitongo",
      "Santiago Tamazola",
      "Santiago Tapextla",
      "Santiago Tenango",
      "Santiago Teotlaxco",
      "Santiago Tepetlapa",
      "Santiago Tetepec",
      "Santiago Texcalcingo",
      "Santiago Textitlán",
      "Santiago Tilantongo",
      "Santiago Tillo",
      "Santiago Tlazoyaltepec",
      "Santiago Xanica",
      "Santiago Xiacuí",
      "Santiago Yaitepec",
      "Santiago Yaveo",
      "Santiago Yolomécatl",
      "Santiago Yosondúa",
      "Santiago Yucuyachi",
      "Santiago Zacatepec",
      "Santiago Zoochila",
      "Santo Domingo Armenta",
      "Santo Domingo Chihuitán",
      "Santo Domingo de Morelos",
      "Santo Domingo Ingenio",
      "Santo Domingo Ixcatlán",
      "Santo Domingo Nuxaá",
      "Santo Domingo Ozolotepec",
      "Santo Domingo Petapa",
      "Santo Domingo Roayaga",
      "Santo Domingo Tehuantepec",
      "Santo Domingo Teojomulco",
      "Santo Domingo Tepuxtepec",
      "Santo Domingo Tlatayápam",
      "Santo Domingo Tomaltepec",
      "Santo Domingo Tonalá",
      "Santo Domingo Tonaltepec",
      "Santo Domingo Xagacía",
      "Santo Domingo Yanhuitlán",
      "Santo Domingo Yodohino",
      "Santo Domingo Zanatepec",
      "Santos Reyes Nopala",
      "Santos Reyes Pápalo",
      "Santos Reyes Tepejillo",
      "Santos Reyes Yucuná",
      "Silacayoápam",
      "Sola de Vega",
      "Tamazulápam del Espíritu Santo",
      "Tanetze de Zaragoza",
      "Taniche",
      "Tataltepec de Valdés",
      "Teococuilco de Marcos Pérez",
      "Teotitlán de Flores Magón",
      "Teotitlán del Valle",
      "Teotongo",
      "Tepelmeme Villa de Morelos",
      "Tlacolula de Matamoros",
      "Tlacotepec Plumas",
      "Tlalixtac de Cabrera",
      "Totontepec Villa de Morelos",
      "Trinidad Zaachila",
      "Unión Hidalgo",
      "Valerio Trujano",
      "Villa de Chilapa de Díaz",
      "Villa de Etla",
      "Villa de Tamazulápam del Progreso",
      "Villa de Tututepec de Melchor Ocampo",
      "Villa de Zaachila",
      "Villa Díaz Ordaz",
      "Villa Hidalgo",
      "Villa Sola de Vega",
      "Villa Talea de Castro",
      "Villa Tejúpam de la Unión",
      "Yaxe",
      "Yogana",
      "Yutanduchi de Guerrero",
      "Zapotitlán Lagunas",
      "Zapotitlán Palmas",
      "Zimatlán de Álvarez",
    ],
  },
  {
    nombre: "Puebla",
    ciudades: [
      // Principales ciudades
      "Puebla de Zaragoza (capital)",
      "Tehuacán",
      "San Martín Texmelucan",
      "Atlixco",
      "Cholula (San Pedro Cholula / San Andrés Cholula)",

      // Municipios importantes (217 municipios total)
      "Acajete",
      "Acateno",
      "Acatlán",
      "Acatzingo",
      "Acteopan",
      "Ahuacatlán",
      "Ahuatlán",
      "Ahuazotepec",
      "Ahuehuetitla",
      "Ajalpan",
      "Albino Zertuche",
      "Aljojuca",
      "Altepexi",
      "Amixtlán",
      "Amozoc",
      "Aquixtla",
      "Atempan",
      "Atexcal",
      "Atlequizayan",
      "Atoyatempan",
      "Atzala",
      "Atzitzihuacán",
      "Atzitzintla",
      "Axutla",
      "Ayotoxco de Guerrero",
      "Calpan",
      "Caltepec",
      "Camocuautla",
      "Caxhuacan",
      "Chalchicomula de Sesma",
      "Chapulco",
      "Chiautla",
      "Chiautzingo",
      "Chiconcuautla",
      "Chietla",
      "Chigmecatitlán",
      "Chignahuapan",
      "Chignautla",
      "Chila",
      "Chila de la Sal",
      "Chinantla",
      "Coatepec",
      "Coatzingo",
      "Cohetzala",
      "Cohuecan",
      "Coronango",
      "Coxcatlán",
      "Coyomeapan",
      "Coyotepec",
      "Cuapiaxtla de Madero",
      "Cuautempan",
      "Cuautinchán",
      "Cuautlancingo",
      "Cuayuca de Andrade",
      "Cuetzalan del Progreso",
      "Cuyoaco",
      "Domingo Arenas",
      "Eloxochitlán",
      "Epatlán",
      "Esperanza",
      "Francisco Z. Mena",
      "General Felipe Ángeles",
      "Guadalupe",
      "Guadalupe Victoria",
      "Hermenegildo Galeana",
      "Honey",
      "Huatlatlauca",
      "Huauchinango",
      "Huehuetla",
      "Huehuetlán el Chico",
      "Huehuetlán el Grande",
      "Huejotzingo",
      "Hueyapan",
      "Hueytamalco",
      "Hueytlalpan",
      "Huitzilan de Serdán",
      "Huitziltepec",
      "Ixcamilpa de Guerrero",
      "Ixcaquixtla",
      "Ixtacamaxtitlán",
      "Ixtepec",
      "Izúcar de Matamoros",
      "Jalpan",
      "Jolalpan",
      "Jonotla",
      "Jopala",
      "Juan C. Bonilla",
      "Juan Galindo",
      "Juan N. Méndez",
      "La Magdalena Tlatlauquitepec",
      "Lafragua",
      "Libres",
      "Los Reyes de Juárez",
      "Mazapiltepec de Juárez",
      "Mixtla",
      "Molcaxac",
      "Naupan",
      "Nauzontla",
      "Nealtican",
      "Nicolás Bravo",
      "Nopalucan",
      "Ocotepec",
      "Ocoyucan",
      "Olintla",
      "Oriental",
      "Pahuatlán",
      "Palmar de Bravo",
      "Pantepec",
      "Petlalcingo",
      "Piaxtla",
      "Puebla",
      "Quecholac",
      "Quimixtlán",
      "Rafael Lara Grajales",
      "San Andrés Cholula",
      "San Antonio Cañada",
      "San Diego la Mesa Tochimiltzingo",
      "San Felipe Teotlalcingo",
      "San Felipe Tepatlán",
      "San Gabriel Chilac",
      "San Gregorio Atzompa",
      "San Jerónimo Tecuanipan",
      "San Jerónimo Xayacatlán",
      "San José Chiapa",
      "San José Miahuatlán",
      "San Juan Atenco",
      "San Juan Atzompa",
      "San Martín Totoltepec",
      "San Matías Tlalancaleca",
      "San Miguel Ixitlán",
      "San Miguel Xoxtla",
      "San Nicolás Buenos Aires",
      "San Nicolás de los Ranchos",
      "San Pablo Anicano",
      "San Pedro Cholula",
      "San Pedro Yeloixtlahuaca",
      "San Salvador el Seco",
      "San Salvador el Verde",
      "San Sebastián Tlacotepec",
      "Santa Catarina Tlaltempan",
      "Santa Inés Ahuatempan",
      "Santa Isabel Cholula",
      "Santiago Miahuatlán",
      "Santo Tomás Hueyotlipan",
      "Soltepec",
      "Tecali de Herrera",
      "Tecamachalco",
      "Tecomatlán",
      "Tehuacán",
      "Tehuitzingo",
      "Tenampulco",
      "Teopantlán",
      "Teotlalco",
      "Tepanco de López",
      "Tepango de Rodríguez",
      "Tepatlaxco de Hidalgo",
      "Tepeaca",
      "Tepemaxalco",
      "Tepeojuma",
      "Tepetzintla",
      "Tepexco",
      "Tepexi de Rodríguez",
      "Tepeyahualco",
      "Tepeyahualco de Cuauhtémoc",
      "Tetela de Ocampo",
      "Teteles de Ávila Castillo",
      "Teziutlán",
      "Tianguismanalco",
      "Tilapa",
      "Tlachichuca",
      "Tlacotepec de Benito Juárez",
      "Tlacuilotepec",
      "Tlahuapan",
      "Tlaltenango",
      "Tlanepantla",
      "Tlaola",
      "Tlapacoya",
      "Tlapanalá",
      "Tlatlauquitepec",
      "Tlaxco",
      "Tochimilco",
      "Tochtepec",
      "Totoltepec de Guerrero",
      "Tulcingo",
      "Tuzamapan de Galeana",
      "Tzicatlacoyan",
      "Venustiano Carranza",
      "Vicente Guerrero",
      "Xayacatlán de Bravo",
      "Xicotepec",
      "Xicotlán",
      "Xiutetelco",
      "Xochiapulco",
      "Xochiltepec",
      "Xochitlán de Vicente Suárez",
      "Xochitlán Todos Santos",
      "Yaonáhuac",
      "Yehualtepec",
      "Zacapala",
      "Zacapoaxtla",
      "Zacatlán",
      "Zapotitlán",
      "Zapotitlán de Méndez",
      "Zaragoza",
      "Zautla",
      "Zihuateutla",
      "Zinacatepec",
      "Zongozotla",
      "Zoquiapan",
      "Zoquitlán",

      // Pueblos Mágicos
      "Cuetzalan del Progreso",
      "Pahuatlán",
      "Tlatlauquitepec",
      "Xicotepec",
      "Zacatlán",

      // Zonas arqueológicas
      "Cholula (Gran Pirámide)",
      "Cantona",
      "Yohualichan",
      "Teteles de Santo Nombre",
      "Tepexi el Viejo",

      // Destinos turísticos
      "Valle de Piedras Encimadas",
      "Grutas de Karmidas",
      "Jardín Botánico Helia Bravo Hollis",
      "Cascadas de Quetzalapa",
      "Laguna de Alchichica",
      "Parque Nacional Izta-Popo",
      "Africam Safari",
      "Estrella de Puebla",
      "Zócalo de Puebla",
      "Barrio del Artista",
      "Fuertes de Loreto y Guadalupe",

      // Ciudades industriales
      "San José Chiapa (Audi)",
      "Corredor Industrial Quetzalcoatl",
      "Parque Industrial FINSA Puebla",
      "Zona Industrial Huejotzingo",
    ],
  },
  {
    nombre: "Querétaro",
    ciudades: [
      // Zona Metropolitana de Querétaro
      "Santiago de Querétaro (capital)",
      "Corregidora",
      "El Marqués",
      "Huimilpan",

      // Principales ciudades
      "San Juan del Río",
      "Tequisquiapan",
      "Ezequiel Montes",
      "Cadereyta de Montes",
      "Jalpan de Serra",
      "Bernal",
      "Amealco de Bonfil",

      // Todos los municipios (18 municipios)
      "Arroyo Seco",
      "Colón",
      "Landa de Matamoros",
      "Pedro Escobedo",
      "Peñamiller",
      "Pinal de Amoles",
      "San Joaquín",
      "Tolimán",

      // Pueblos Mágicos
      "Tequisquiapan",
      "Bernal",
      "Jalpan de Serra",
      "Cadereyta de Montes",
      "San Joaquín",

      // Zonas arqueológicas
      "El Cerrito (pirámide)",
      "Ranas",
      "Toluquilla",

      // Parques industriales importantes
      "Parque Industrial Querétaro",
      "Parque Industrial Benito Juárez",
      "Parque Industrial El Marqués",
      "Parque Industrial FINSA",
      "Parque Industrial Aeropuerto",

      // Áreas naturales y turísticas
      "Sierra Gorda (reserva de la biosfera)",
      "Peña de Bernal",
      "Viñedos de Freixenet",
      "Viñedos La Redonda",
      "Misión Concá",
      "Grutas de los Herrera",
      "Presa Jalpan",
      "Cascada Chuveje",
      "Sótano del Barro",

      // Poblaciones con encanto
      "La Cañada",
      "Bucareli",
      "Pinal de Amoles",
      "Concá",
      "San Pedro Tenango",
      "Tancama",
      "Vizarrón",
      "El Lobo",
      "La Griega",
      "El Rincón",

      // Nuevos desarrollos urbanos
      "Juriquilla",
      "Zibata",
      "Hacienda Santa Rosa",
      "Villas del Mesón",
      "Balvanera",
      "El Refugio",
    ],
  },
  {
    nombre: "Quintana Roo",
    ciudades: [
      // Principales destinos turísticos
      "Cancún",
      "Playa del Carmen",
      "Chetumal (capital)",
      "Tulum",
      "Cozumel",

      // Municipios (11 en total)
      "Benito Juárez (Cancún)",
      "Solidaridad (Playa del Carmen)",
      "Othón P. Blanco (Chetumal)",
      "Cozumel",
      "Felipe Carrillo Puerto",
      "Isla Mujeres",
      "Bacalar",
      "José María Morelos",
      "Lázaro Cárdenas",
      "Puerto Morelos",
      "Tulum",

      // Islas y cayos importantes
      "Isla Holbox",
      "Isla Contoy",
      "Banco Chinchorro",
      "Cayo Culebra",
      "Cayo Venado",
      "Isla Blanca",
      "Isla Passion",

      // Zonas arqueológicas
      "Cobá",
      "Muyil",
      "Kohunlich",
      "Dzibanché",
      "Kinichná",
      "El Rey",
      "El Meco",
      "San Gervasio",

      // Playas y destinos costeros
      "Akumal",
      "Puerto Aventuras",
      "Xpu-Há",
      "Xcacel-Xcacelito",
      "Punta Allen",
      "Mahahual",
      "Xcalak",
      "Sian Ka'an",
      "Punta Maroma",
      "Punta Bete",
      "Playa del Secreto",
      "Playa Paraíso",
      "Playa Norte (Isla Mujeres)",

      // Pueblos con encanto
      "Bacalar",
      "Felipe Carrillo Puerto",
      "Holbox",
      "Kantunilkín",
      "Tihosuco",
      "Chunhuhub",
      "Nicolás Bravo",

      // Áreas naturales protegidas
      "Reserva de la Biosfera Sian Ka'an",
      "Parque Nacional Arrecifes de Cozumel",
      "Parque Nacional Costa Occidental",
      "Área de Protección de Flora y Fauna Yum Balam",
      "Reserva Estatal Santuario del Manatí",
      "Laguna de Bacalar",
      "Cenote Azul",
      "Río Hondo",

      // Nuevos desarrollos turísticos
      "Puerto Cancún",
      "Kanai",
      "Tren Maya (estaciones principales)",
      "Alaia",
      "Playa Mujeres",
      "Costa Mujeres",
      "Mayakoba",
    ],
  },
  {
    nombre: "San Luis Potosí",
    ciudades: [
      // Zona Metropolitana
      "San Luis Potosí (capital)",
      "Soledad de Graciano Sánchez",

      // Principales ciudades
      "Ciudad Valles",
      "Matehuala",
      "Rioverde",

      // Todos los municipios (58 municipios)
      "Ahualulco",
      "Alaquines",
      "Aquismón",
      "Armadillo de los Infante",
      "Axtla de Terrazas",
      "Cárdenas",
      "Catorce",
      "Cedral",
      "Cerritos",
      "Cerro de San Pedro",
      "Charcas",
      "Ciudad del Maíz",
      "Coxcatlán",
      "Ebano",
      "El Naranjo",
      "Guadalcázar",
      "Huehuetlán",
      "Lagunillas",
      "Mexquitic de Carmona",
      "Moctezuma",
      "Rayón",
      "Salinas",
      "San Antonio",
      "San Ciro de Acosta",
      "San Martín Chalchicuautla",
      "San Nicolás Tolentino",
      "Santa Catarina",
      "Santa María del Río",
      "Santo Domingo",
      "San Vicente Tancuayalab",
      "Tamasopo",
      "Tamazunchale",
      "Tampacán",
      "Tampamolón Corona",
      "Tamuín",
      "Tancanhuitz de Santos",
      "Tanlajás",
      "Tanquián de Escobedo",
      "Tierra Nueva",
      "Vanegas",
      "Venado",
      "Villa de Arista",
      "Villa de Arriaga",
      "Villa de Guadalupe",
      "Villa de la Paz",
      "Villa de Ramos",
      "Villa de Reyes",
      "Villa Hidalgo",
      "Villa Juárez",
      "Xilitla",
      "Zaragoza",

      // Pueblos Mágicos
      "Real de Catorce",
      "Xilitla",
      "Santa María del Río",

      // Zonas arqueológicas
      "Tamohi (Tamuín)",
      "El Consuelo (Tamuín)",
      "Tantoc (Rioverde)",

      // Áreas naturales
      "Sótano de las Golondrinas (Aquismón)",
      "Cascadas de Micos (Ciudad Valles)",
      "Laguna de la Media Luna (Rioverde)",
      "Grutas de la Catedral (El Naranjo)",
      "Parque Nacional El Potosí",
      "Reserva de la Biosfera Sierra del Abra Tanchipa",

      // Ciudades industriales
      "Villa de Reyes (Parque Industrial)",
      "Soledad de Graciano Sánchez (Zona Industrial)",
      "San Luis Potosí (Corredor Industrial)",

      // Poblaciones huastecas importantes
      "Aquismón",
      "Tancanhuitz",
      "Tampamolón",
      "Huehuetlán",
      "Axtla de Terrazas",

      // Zonas mineras
      "Cerro de San Pedro",
      "Charcas",
      "Catorce",
      "Villa de la Paz",
    ],
  },
  {
    nombre: "Sinaloa",
    ciudades: [
      // Principales ciudades
      "Culiacán Rosales (capital)",
      "Mazatlán",
      "Los Mochis",
      "Guamúchil",
      "Navolato",

      // Todos los municipios (18 municipios)
      "Ahome",
      "Angostura",
      "Badiraguato",
      "Concordia",
      "Cosalá",
      "Choix",
      "El Fuerte",
      "Escuinapa",
      "Elota",
      "Guasave",
      "Mocorito",
      "Rosario",
      "Salvador Alvarado",
      "San Ignacio",
      "Sinaloa",
      "Navolato",

      // Pueblos Mágicos
      "Cosalá",
      "El Fuerte",
      "Mocorito",

      // Zonas turísticas importantes
      "Costa de Oro (Guasave)",
      "Isla de la Piedra (Mazatlán)",
      "Pueblo Viejo (Navolato)",
      "La Noria (Mazatlán)",
      "Quelite (Concordia)",
      "El Quelite (Mocorito)",
      "El Habal (Mazatlán)",
      "Altata (Navolato)",
      "Bacamacari (Culiacán)",

      // Valles agrícolas
      "Valle del Carrizo (Guamúchil)",
      "Valle del Fuerte (Los Mochis)",
      "Valle de Culiacán",
      "Valle de Guasave",
      "Valle del Évora",

      // Playas y destinos costeros
      "Playa Las Glorias (Guasave)",
      "Playa Ceuta (Elota)",
      "Playa Las Labradas (San Ignacio)",
      "Playa El Maviri (Los Mochis)",
      "Playa El Caimanero (Escuinapa)",
      "Playa Las Brujas (Mazatlán)",
      "Playa Olas Altas (Mazatlán)",
      "Playa Norte (Mazatlán)",

      // Zonas arqueológicas
      "Las Labradas (San Ignacio)",
      "Chametla (Rosario)",
      "Cosalá (Museo de Minería)",

      // Áreas naturales
      "Marismas Nacionales (Escuinapa)",
      "Sierra de Sinaloa (Badiraguato)",
      "Cerro de la Máscara (Cosalá)",
      "Presa Miguel Hidalgo (El Fuerte)",
      "PresaLópez Mateos (Elota)",

      // Ciudades industriales
      "Topolobampo (Puerto)",
      "Parque Industrial Culiacán",
      "Zona Industrial Mazatlán",
      "Parque Industrial Guamúchil",

      // Poblaciones con tradición cultural
      "Pericos (Mocorito)",
      "Siqueros (Concordia)",
      "El Dorado (Culiacán)",
      "El Verde (Culiacán)",
      "El Tamarindo (Escuinapa)",
    ],
  },
  {
    nombre: "Sonora",
    ciudades: [
      "Aconchi",
      "Agua Prieta",
      "Álamos",
      "Altar",
      "Arivechi",
      "Arizpe",
      "Atil",
      "Bacadéhuachi",
      "Bacanora",
      "Bacerac",
      "Bacoachi",
      "Bácum",
      "Banámichi",
      "Baviácora",
      "Bavispe",
      "Benito Juárez",
      "Benjamín Hill",
      "Caborca",
      "Cajeme (Ciudad Obregón)",
      "Cananea",
      "Carbó",
      "Cucurpe",
      "Cumpas",
      "Divisaderos",
      "Empalme",
      "Etchojoa",
      "Fronteras",
      "General Plutarco Elías Calles",
      "Granados",
      "Guaymas",
      "Hermosillo",
      "Huachinera",
      "Huásabas",
      "Huatabampo",
      "Huépac",
      "Imuris",
      "La Colorada",
      "Magdalena",
      "Mazatán",
      "Moctezuma",
      "Naco",
      "Nácori Chico",
      "Nacozari de García",
      "Navojoa",
      "Nogales",
      "Onavas",
      "Opodepe",
      "Oquitoa",
      "Pitiquito",
      "Puerto Peñasco",
      "Quiriego",
      "Rayón",
      "Rosario",
      "Sahuaripa",
      "San Felipe de Jesús",
      "San Ignacio Río Muerto",
      "San Javier",
      "San Luis Río Colorado",
      "San Miguel de Horcasitas",
      "San Pedro de la Cueva",
      "Santa Ana",
      "Sáric",
      "Soyopa",
      "Suaqui Grande",
      "Tepache",
      "Trincheras",
      "Tubutama",
      "Ures",
      "Villa Hidalgo",
      "Villa Pesqueira",
      "Yécora",
    ],
  },
  {
    nombre: "Tabasco",
    ciudades: [
      "Balancán",
      "Cárdenas",
      "Centla",
      "Centro (Villahermosa)",
      "Comalcalco",
      "Cunduacán",
      "Emiliano Zapata",
      "Huimanguillo",
      "Jalapa",
      "Jalpa de Méndez",
      "Jonuta",
      "Macuspana",
      "Nacajuca",
      "Paraíso",
      "Tacotalpa",
      "Teapa",
      "Tenosique",
    ],
  },
  {
    nombre: "Tlaxcala",
    ciudades: [
      "Amaxac de Guerrero",
      "Apetatitlán de Antonio Carvajal",
      "Apizaco",
      "Atlangatepec",
      "Altzayanca",
      "Benito Juárez",
      "Calpulalpan",
      "Chiautempan",
      "Contla de Juan Cuamatzi",
      "Cuapiaxtla",
      "Cuaxomulco",
      "El Carmen Tequexquitla",
      "Emiliano Zapata",
      "Españita",
      "Huamantla",
      "Hueyotlipan",
      "Ixtacuixtla de Mariano Matamoros",
      "Ixtenco",
      "La Magdalena Tlaltelulco",
      "Lázaro Cárdenas",
      "Nanacamilpa de Mariano Arista",
      "Nativitas",
      "Panotla",
      "Papalotla de Xicohténcatl",
      "San Damián Texóloc",
      "San Francisco Tetlanohcan",
      "San Jerónimo Zacualpan",
      "San José Teacalco",
      "San Juan Huactzinco",
      "San Lorenzo Axocomanitla",
      "San Lucas Tecopilco",
      "San Pablo del Monte",
      "Sanctórum de Lázaro Cárdenas",
      "Santa Ana Nopalucan",
      "Santa Apolonia Teacalco",
      "Santa Catarina Ayometla",
      "Santa Cruz Quilehtla",
      "Santa Cruz Tlaxcala",
      "Santa Isabel Xiloxoxtla",
      "Tenancingo",
      "Teolocholco",
      "Tepetitla de Lardizábal",
      "Tepeyanco",
      "Terrenate",
      "Tetla de la Solidaridad",
      "Tetlatlahuca",
      "Tlaxcala",
      "Tlaxco",
      "Tocatlán",
      "Totolac",
      "Tzompantepec",
      "Xaloztoc",
      "Xaltocan",
      "Xicohtzinco",
      "Yauhquemehcan",
      "Zacatelco",
      "Ziltlaltépec de Trinidad Sánchez Santos",
    ],
  },
  {
    nombre: "Veracruz",
    ciudades: [
      "Acajete",
      "Acatlán",
      "Acayucan",
      "Actopan",
      "Acula",
      "Acultzingo",
      "Agua Dulce",
      "Álamo Temapache",
      "Alpatláhuac",
      "Alto Lucero de Gutiérrez Barrios",
      "Altotonga",
      "Alvarado",
      "Amatitlán",
      "Amatlán de los Reyes",
      "Angel R. Cabada",
      "Apazapan",
      "Aquila",
      "Astacinga",
      "Atlahuilco",
      "Atoyac",
      "Atzacan",
      "Atzalan",
      "Ayahualulco",
      "Banderilla",
      "Benito Juárez",
      "Boca del Río",
      "Calcahualco",
      "Camarón de Tejeda",
      "Camerino Z. Mendoza",
      "Carlos A. Carrillo",
      "Carrillo Puerto",
      "Castillo de Teayo",
      "Catemaco",
      "Cazones de Herrera",
      "Cerro Azul",
      "Chacaltianguis",
      "Chalma",
      "Chiconamel",
      "Chiconquiaco",
      "Chicontepec",
      "Chinameca",
      "Chinampa de Gorostiza",
      "Chocamán",
      "Chontla",
      "Chumatlán",
      "Citlaltépetl",
      "Coacoatzintla",
      "Coahuitlán",
      "Coatepec",
      "Coatzacoalcos",
      "Coatzintla",
      "Coetzala",
      "Colipa",
      "Comapa",
      "Córdoba",
      "Cosamaloapan de Carpio",
      "Cosautlán de Carvajal",
      "Coscomatepec",
      "Cosoleacaque",
      "Cotaxtla",
      "Coxquihui",
      "Coyutla",
      "Cuichapa",
      "Cuitláhuac",
      "El Higo",
      "Emiliano Zapata",
      "Espinal",
      "Filomeno Mata",
      "Fortín",
      "Gutiérrez Zamora",
      "Hidalgotitlán",
      "Huatusco",
      "Huayacocotla",
      "Hueyapan de Ocampo",
      "Huiloapan de Cuauhtémoc",
      "Ignacio de la Llave",
      "Ilamatlán",
      "Isla",
      "Ixcatepec",
      "Ixhuacán de los Reyes",
      "Ixhuatlán del Café",
      "Ixhuatlancillo",
      "Ixhuatlán del Sureste",
      "Ixhuatlán de Madero",
      "Ixmatlahuacan",
      "Ixtaczoquitlán",
      "Jalacingo",
      "Jalcomulco",
      "Jáltipan",
      "Jamapa",
      "Jesús Carranza",
      "Jilotepec",
      "José Azueta",
      "Juan Rodríguez Clara",
      "Juchique de Ferrer",
      "La Antigua",
      "La Perla",
      "Landero y Coss",
      "Lerdo de Tejada",
      "Magdalena",
      "Maltrata",
      "Manlio Fabio Altamirano",
      "Mariano Escobedo",
      "Martínez de la Torre",
      "Mecatlán",
      "Mecayapan",
      "Medellín",
      "Miahuatlán",
      "Minatitlán",
      "Misantla",
      "Mixtla de Altamirano",
      "Moloacán",
      "Nanchital",
      "Naolinco",
      "Naranjal",
      "Naranjos Amatlán",
      "Nautla",
      "Nogales",
      "Oluta",
      "Omealca",
      "Orizaba",
      "Otatitlán",
      "Oteapan",
      "Ozuluama de Mascareñas",
      "Pajapan",
      "Pánuco",
      "Papantla",
      "Paso de Ovejas",
      "Paso del Macho",
      "Perote",
      "Platón Sánchez",
      "Playa Vicente",
      "Poza Rica de Hidalgo",
      "Pueblo Viejo",
      "Puente Nacional",
      "Rafael Delgado",
      "Rafael Lucio",
      "Los Reyes",
      "Río Blanco",
      "Saltabarranca",
      "San Andrés Tenejapan",
      "San Andrés Tuxtla",
      "San Juan Evangelista",
      "Santiago Tuxtla",
      "Sayula de Alemán",
      "Sochiapa",
      "Soconusco",
      "Soledad Atzompa",
      "Soledad de Doblado",
      "Soteapan",
      "Tamalín",
      "Tamiahua",
      "Tampico Alto",
      "Tancoco",
      "Tantima",
      "Tantoyuca",
      "Tatahuicapan de Juárez",
      "Tatatila",
      "Tecolutla",
      "Tehuipango",
      "Tempoal",
      "Tenampa",
      "Tenochtitlán",
      "Teocelo",
      "Tepatlaxco",
      "Tepetlán",
      "Tepetzintla",
      "Tequila",
      "Texcatepec",
      "Texhuacán",
      "Texistepec",
      "Tezonapa",
      "Tierra Blanca",
      "Tihuatlán",
      "Tlacojalpan",
      "Tlacolulan",
      "Tlacotalpan",
      "Tlacotepec de Mejía",
      "Tlachichilco",
      "Tlalixcoyan",
      "Tlalnelhuayocan",
      "Tlaltetela",
      "Tlapacoyan",
      "Tlaquilpa",
      "Tlilapan",
      "Tomatlán",
      "Tonayán",
      "Totutla",
      "Tres Valles",
      "Túxpam",
      "Tuxtilla",
      "Ursulo Galván",
      "Vega de Alatorre",
      "Veracruz",
      "Villa Aldama",
      "Xalapa",
      "Xico",
      "Xoxocotla",
      "Yanga",
      "Yecuatla",
      "Zacualpan",
      "Zaragoza",
      "Zentla",
      "Zongolica",
      "Zontecomatlán de López y Fuentes",
      "Zozocolco de Hidalgo",
    ],
  },
  {
    nombre: "Yucatán",
    ciudades: [
      "Abalá",
      "Acanceh",
      "Akil",
      "Baca",
      "Bokobá",
      "Buctzotz",
      "Cacalchén",
      "Calotmul",
      "Cansahcab",
      "Cantamayec",
      "Celestún",
      "Cenotillo",
      "Chacsinkín",
      "Chankom",
      "Chapab",
      "Chemax",
      "Chichimilá",
      "Chicxulub Pueblo",
      "Chikindzonot",
      "Chocholá",
      "Chumayel",
      "Conkal",
      "Cuncunul",
      "Cuzamá",
      "Dzán",
      "Dzemul",
      "Dzidzantún",
      "Dzilam de Bravo",
      "Dzilam González",
      "Dzitás",
      "Dzoncauich",
      "Espita",
      "Halachó",
      "Hocabá",
      "Hoctún",
      "Homún",
      "Huhí",
      "Hunucmá",
      "Ixil",
      "Izamal",
      "Kanasín",
      "Kantunil",
      "Kaua",
      "Kinchil",
      "Kopomá",
      "Mama",
      "Maní",
      "Maxcanú",
      "Mayapán",
      "Mérida",
      "Mocochá",
      "Motul",
      "Muna",
      "Muxupip",
      "Opichén",
      "Oxkutzcab",
      "Panabá",
      "Peto",
      "Progreso",
      "Quintana Roo",
      "Río Lagartos",
      "Sacalum",
      "Samahil",
      "Sanahcat",
      "San Felipe",
      "Santa Elena",
      "Seyé",
      "Sinanché",
      "Sotuta",
      "Sucilá",
      "Sudzal",
      "Suma",
      "Tahdziú",
      "Tahmek",
      "Teabo",
      "Tecoh",
      "Tekal de Venegas",
      "Tekantó",
      "Tekax",
      "Tekit",
      "Tekom",
      "Telchac Pueblo",
      "Telchac Puerto",
      "Temax",
      "Temozón",
      "Tepakán",
      "Tetiz",
      "Teya",
      "Ticul",
      "Timucuy",
      "Tinum",
      "Tixcacalcupul",
      "Tixkokob",
      "Tixméhuac",
      "Tixpéhual",
      "Tizimín",
      "Tunkás",
      "Tzucacab",
      "Uayma",
      "Ucú",
      "Umán",
      "Valladolid",
      "Xocchel",
      "Yaxcabá",
      "Yaxkukul",
      "Yobaín",
    ],
  },
  {
    nombre: "Zacatecas",
    ciudades: [
      "Apozol",
      "Apulco",
      "Atolinga",
      "Benito Juárez",
      "Calera",
      "Cañitas de Felipe Pescador",
      "Chalchihuites",
      "Concepción del Oro",
      "Cuauhtémoc",
      "El Plateado de Joaquín Amaro",
      "El Salvador",
      "Fresnillo",
      "Genaro Codina",
      "General Enrique Estrada",
      "General Francisco R. Murguía",
      "General Pánfilo Natera",
      "Guadalupe",
      "Huanusco",
      "Jalpa",
      "Jerez",
      "Jiménez del Teul",
      "Juan Aldama",
      "Juchipila",
      "Loreto",
      "Luis Moya",
      "Mazapil",
      "Melchor Ocampo",
      "Mezquital del Oro",
      "Miguel Auza",
      "Momax",
      "Monte Escobedo",
      "Morelos",
      "Moyahua de Estrada",
      "Nochistlán de Mejía",
      "Noria de Ángeles",
      "Ojocaliente",
      "Pánuco",
      "Pinos",
      "Río Grande",
      "Sain Alto",
      "Santa María de la Paz",
      "Sombrerete",
      "Susticacán",
      "Tabasco",
      "Tepechitlán",
      "Tepetongo",
      "Teúl de González Ortega",
      "Tlaltenango de Sánchez Román",
      "Trancoso",
      "Trinidad García de la Cadena",
      "Valparaíso",
      "Vetagrande",
      "Villa de Cos",
      "Villa García",
      "Villa González Ortega",
      "Villa Hidalgo",
      "Villanueva",
      "Zacatecas",
    ],
  },
];
